// <auto-generated />
using System;
using BasicApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240812120119_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasicApp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Age = 21,
                            IsActive = true,
                            Name = "Igor"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Age = 19,
                            IsActive = false,
                            Name = "Szymon"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Age = 45,
                            IsActive = true,
                            Name = "Magdalena"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Age = 48,
                            IsActive = false,
                            Name = "Michał"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
